services:
  - type: web
    name: mynextbook
    env: docker
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: mynextbook-db
    databaseName: mynextbook_production
    user: mynextbook
