services:
  - type: web
    name: mynextbook
    env: docker
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_DOMAIN
        value: mynextbook.buildsandchill.com
      - key: MAILER_SENDER
        value: noreply@mynextbook.com

databases:
  - name: mynextbook-db
    databaseName: mynextbook_production
    user: mynextbook
