# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Development environment
# Uses Neon database via DATABASE_URL environment variable
development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# Test environment
# Uses local database for testing
test:
  <<: *default
  database: my_next_book_test
  username: my_next_book
  password: password123
  host: localhost
  port: 5432

# Production environment
# Uses Render database via DATABASE_URL environment variable
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
