# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Configuration par défaut - sera écrasée par les fichiers spécifiques
development:
  <<: *default
  url: <%= ENV['DATABASE_URL_DEV'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL_DEV'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_PROD'] %>
